# Generated by Django 5.0.6 on 2024-05-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.CharField(max_length=300, verbose_name='Описание')),
                ('stat', models.CharField(choices=[('max_hp', 'Максимальный запас здоровья'), ('current_hp', 'Текущий запас здоровья'), ('max_mp', 'Максимальный запас маны'), ('current_mp', 'Текущий запас маны'), ('max_sp', 'Максимальный запас выносливости'), ('current_sp', 'Текущий запас выносливости'), ('physical_damage', 'Физический урон'), ('magical_damage', 'Магический урон'), ('physical_defense', 'Защита от физического урона'), ('magical_defense', 'Защита от магического урона'), ('reaction_speed', 'Скорость реакции'), ('movement_speed', 'Скорость передвижения'), ('critical_hit_chance', 'Шанс на критический удар'), ('pierce_chance', 'Шанс на пронзающий удар'), ('physical_damage_block_chance', 'Шанс на блокирование физического урона'), ('physical_damage_reflect_chance', 'Шанс на отражение физического урона'), ('dodge_chance', 'Шанс на уворот от атаки'), ('luck', 'Удача'), ('experience_point', 'Опыт'), ('level', 'Уровень')], max_length=30, verbose_name='Целевой показатель')),
                ('direction', models.CharField(choices=[('positive', 'Положительный'), ('negative', 'Отрицательный')], max_length=8, verbose_name='Вектор')),
                ('calculation_method', models.CharField(choices=[('addition', 'Сложение'), ('multiplication', 'Умножение')], max_length=14, verbose_name='Метод калькулирования')),
                ('value', models.FloatField(verbose_name='Значение')),
                ('duration', models.IntegerField(verbose_name='Длительность эффекта (ходов)')),
                ('is_infinite', models.BooleanField(default=False, verbose_name='Перманентный эффект')),
            ],
            options={
                'verbose_name': 'Эффект',
                'verbose_name_plural': 'Эффекты',
                'ordering': ['name'],
            },
        ),
    ]
