# Generated by Django 5.0.6 on 2024-05-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effect',
            name='stat',
            field=models.CharField(choices=[('max_hp', 'Максимальный запас здоровья'), ('current_hp', 'Текущий запас здоровья'), ('max_mp', 'Максимальный запас маны'), ('current_mp', 'Текущий запас маны'), ('max_sp', 'Максимальный запас выносливости'), ('current_sp', 'Текущий запас выносливости'), ('satiety', 'Сытость'), ('physical_damage', 'Физический урон'), ('magical_damage', 'Магический урон'), ('physical_defense', 'Защита от физического урона'), ('magical_defense', 'Защита от магического урона'), ('reaction_speed', 'Скорость реакции'), ('movement_speed', 'Скорость передвижения'), ('critical_hit_chance', 'Шанс на критический удар'), ('pierce_chance', 'Шанс на пронзающий удар'), ('physical_damage_block_chance', 'Шанс на блокирование физического урона'), ('physical_damage_reflect_chance', 'Шанс на отражение физического урона'), ('dodge_chance', 'Шанс на уворот от атаки'), ('luck', 'Удача'), ('experience_points', 'Опыт'), ('level', 'Уровень')], max_length=30, verbose_name='Целевой показатель'),
        ),
    ]
